[project]
name = "pandas-ta"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "numba>=0.59.0",
    "numpy>=1.26.4",
    "pandas>=2.2.0",
    "pandas-datareader>=0.10.0",
    "scipy>=1.12",
]

[dependency-groups]
dev = [
    "ruff>=0.12.2",
]

[tool.ruff.lint]
ignore = ["E402", "F403", "F841", "F405"]
#select = ["NPY201"]
